# Generated by Django 6.0.1 on 2026-02-06 18:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('markets', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_sku', models.CharField(db_index=True, max_length=50, verbose_name='SKU Tienda')),
                ('product_url', models.URLField(blank=True, max_length=500, null=True)),
                ('price', models.IntegerField(verbose_name='Precio Oferta (Actual)')),
                ('normal_price', models.IntegerField(blank=True, null=True, verbose_name='Precio Normal')),
                ('card_price', models.IntegerField(blank=True, null=True, verbose_name='Precio Club/Tarjeta')),
                ('price_per_unit', models.CharField(blank=True, max_length=100, null=True, verbose_name='Precio x Unidad')),
                ('discount_percent', models.IntegerField(default=0)),
                ('is_offer', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('stock', models.IntegerField(default=0)),
                ('dynamic_data', models.JSONField(blank=True, default=dict, verbose_name='Datos Variables')),
                ('scraped_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='markets.branch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='products.product')),
            ],
            options={
                'verbose_name': 'Historial de Precio',
                'verbose_name_plural': 'Historial de Precios',
                'ordering': ['-scraped_at'],
                'indexes': [models.Index(fields=['product', 'branch', 'scraped_at'], name='prices_pric_product_3cf8cc_idx')],
            },
        ),
    ]
