# Generated by Django 6.0.1 on 2026-02-06 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ean', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True, verbose_name='Código EAN')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre Global')),
                ('brand', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Marca')),
                ('measurement_unit', models.CharField(blank=True, max_length=20, null=True)),
                ('unit_multiplier', models.FloatField(default=1.0)),
                ('package_format', models.CharField(blank=True, help_text='Ej: 1 Kg', max_length=100, null=True)),
                ('img_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
